<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2021-04-09T18:52:45+02:00" hostname="https://data-java-1583-dev-ed.cs101.my.salesforce.com/" tests="1" failures="1"  errors="0"  time="0.96">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Apr 9, 2021 6:52 PM"/>
            <property name="testExecutionTime" value="0.96 s"/>
            <property name="testTotalTime" value="0.96 s"/>
            <property name="commandTime" value="3.7 s"/>
            <property name="hostname" value="https://data-java-1583-dev-ed.cs101.my.salesforce.com/"/>
            <property name="orgId" value="00D1X0000002tFWUAY"/>
            <property name="username" value="test-grt3b54ezt0d@example.com"/>
            <property name="testRunId" value="7071X00001WeCAw"/>
            <property name="userId" value="0051X000007M7fFQAS"/>
        </properties>
        <testcase name="should_aggregate_two_orders_on_account" classname="TestUpdateAccountTurnover" time="0.96">
            <failure message="System.DmlException: Update failed. First exception on row 0 with id 8011X000002QTcRQAW; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, CalculMontant: execution of BeforeUpdate

caused by: System.NullPointerException: Argument cannot be null.

Trigger.CalculMontant: line 4, column 1: []"><![CDATA[Class.TestUpdateAccountTurnover.should_aggregate_two_orders_on_account: line 54, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
